root_package: SampleIndustry
model_package: Model
test_package: Test
source: ./sample_recipie/sample_industry.xml
parser: drawio
dest_root: ./build/sample_drawio_output
templates_folder: ./sample_recipie/templates
generation_type: spring data rest
model_templates:
# Java: JHipster
- dest: jdl{{package.path}}{{package.name}}.jdl
  level: package
  source: entities.jdl.jinja
# Java: Spring Data Rest
- dest: java/entities{{cls.package.path}}{{cls.name}}.java
  level: class
  source: pojos.java.jinja
- dest: java/enums{{enum.package.path}}{{enum.name}}.java
  level: enumeration
  source: enums.java.jinja
# Documentation
- dest: base.txt
  level: root
  source: base.txt.jinja
test_templates:
- dest: ./build/sample_output{{ins.package.path}}/{{ins.stereotype}}.json
  format: json
