root_package: SampleIndustry
model_package: Model
test_package: Test
source: ./sample_recipie/sample_industry.xmi
parser: sparx
dest_root: ./build/sample_sparx_django
templates_folder: ./sample_recipie/templates
generation_type: django
model_templates:
# Avro Schema
- dest: "avro/{{cls.package.name}}.{{ cls.name }}.avsc"
  level: class
  source: "avro.avsc.jinja"
# Python: Django App
- dest: "{{package.path}}/models.py"
  level: package
  source: Django/app/models.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
- dest: "{{package.path}}/admin.py"
  level: package
  source: Django/app/admin.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
- dest: "{{package.path}}/serializers.py"
  level: package
  source: Django/app/serializers.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
- dest: "{{package.path}}/urls.py"
  level: package
  source: Django/app/urls.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
- dest: "{{package.path}}/views.py"
  level: package
  source: Django/app/views.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
- dest: "{{package.path}}/__init__.py"
  level: package
  source: Django/app/__init__.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
- dest: "{{package.path}}/apps.py"
  level: package
  source: Django/app/apps.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
# Python: Django Project
- dest: "{{ package.path }}{{ package.path.split('/')[1] | snakecase }}/settings.py"
  level: root
  source: Django/project/settings.py.jinja
- dest: "{{ package.path }}{{ package.path.split('/')[1] | snakecase }}/urls.py"
  level: root
  source: Django/project/urls.py.jinja
- dest: "{{ package.path }}{{ package.path.split('/')[1] | snakecase }}/__init__.py"
  level: root
  source: Django/project/__init__.py
- dest: "{{ package.path }}{{ package.path.split('/')[1] | snakecase }}/wsgi.py"
  level: root
  source: Django/project/wsgi.py.jinja
- dest: "{{ package.path }}{{ package.path.split('/')[1] | snakecase }}/asgi.py"
  level: root
  source: Django/project/asgi.py.jinja
- dest: "{{ package.path }}/manage.py"
  level: root
  source: Django/manage.py.jinja
- dest: "{{ package.path }}/requirements.txt"
  level: root
  source: Django/requirements.txt.jinja
# Python: Templates
- dest: "{{ package.path }}/templates/admin/base_site.html"
  level: copy
  source: Django/templates/admin/base_site.html
- dest: "{{ package.path }}/templates/drf-yasg/swagger-ui.html"
  level: copy
  source: Django/templates/drf-yasg/swagger-ui.html
- dest: "{{ package.path }}/templates/rest_framework/api.html"
  level: copy
  source: Django/templates/rest_framework/api.html
test_templates:
- dest: ./build/sample_sparx_django/json{{ins.package.path}}/{{ins.stereotype}}.json
  format: json
