root_package: SampleIndustry
model_package: Model
test_package: Test
source: ./sample_recipies/sample_industry.xmi
parser: sparx
dest_root: ./build/sample_sparx_docs
templates_folder: ./mdg/templates
generation_type: default
model_templates:
- dest: base.txt
  level: root
  source: base.txt.jinja
test_templates:
