root_package: SampleIndustry
model_package: Model
test_package: Test
source: ./sample_recipies/sample_industry.xmi
parser: sparx
dest_root: ./build/
templates_folder: ./templates
generation_type: sqlalchemy
model_templates:
# Python: SQL Alchemy
- dest: "sqlalchemy{{package.path | case_package}}/models.py"
  level: package
  source: sqlalchemy/models.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
- dest: "sqlalchemy{{package.path | case_package}}/schemas.py"
  level: package
  source: sqlalchemy/schemas.py.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
test_templates:
- dest: ./build/json{{ins.package.path}}/{{ins.stereotype}}.json
  format: json
