root_package: SampleIndustry
model_package: Model
test_package: Test
source: ./sample_recipes/sparx/sample_industry.xmi
parser: sparx
dest_root: ./build/sample_sparx_schema
templates_folder: ./mdg/templates
dialect: default
model_templates:
# Avro Schema
- dest: "avro/{{cls.package.name}}.{{ cls.name }}.avsc"
  level: class
  source: "Schema/avro.avsc.jinja"
# OpenAPI Schema
- dest: "openapi/{{ package.name }}.yaml"
  level: package
  source: Schema/openapi.yaml.jinja
  filter: "{% if package.classes %}True{% else %}False{% endif %}"
test_templates:
