model_package: "{D6D3BF36-E897-4a8b-8CA9-62ADAAD696ED}"
test_package: "{C2E30D48-F8AB-4c6f-9FA3-AFE44653D5EB}"
source: sqlite:///./sample_recipes/sparxdb/sample.qea
parser: sparxdb
dest_root: ./build/sample_sparxdb_graphql
templates_folder: ./mdg/templates
generation_type: default
model_templates:
# Hasura Schema
- dest: "{{package.children[0].name | snakecase}}__metadata.json"
  level: root
  source: "hasura.json.jinja"
test_templates:
- dest: "build/test/{{ins.package.path}}/{{ins.stereotype}}.json"
  format: json
