model_package: Model
root_package: SampleIndustry
source: ./test_recipie/sample_industry.xmi
templates_folder: ./test_recipie/templates
templates:
- dest: ./build/test_output/python{{package.path}}/models.py
  level: package
  source: models.py
- dest: ./build/test_output/jdl{{package.path}}{{package.name}}.jdl
  level: package
  source: entities.jdl
- dest: ./build/test_output/java/entities{{cls.package.path}}{{cls.name}}.java
  level: class
  source: pojos.java
- dest: ./build/test_output/java/enums{{enum.package.path}}{{enum.name}}.java
  level: enumeration
  source: enums.java
test_package: Test
test_templates:
- dest: ./build/test_output{{ins.package.path}}/{{ins.stereotype}}.json
  format: json
generation_type: default
